# Configuration for KU-HAR dataset
name: PTB-XL
huggingface: BLOSSOM-framework/PTB-XL 
task:
  _target_: blossom.benchmarks.ptbxl.task.get_task
dataset_class:
  _target_: blossom.benchmarks.ptbxl.dataloader.get_dataset_class
encoders_dict:
  _target_: blossom.benchmarks.ptbxl.models.get_encoders_dict
fusion_module:
  _target_: blossom.benchmarks.ptbxl.models.get_fusion_module
head_module:
  _target_: blossom.benchmarks.ptbxl.models.get_head_module 
partition_by:
  _target_: blossom.benchmarks.ptbxl.task.get_partition_by